
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: LS One
        run: ls
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.APT || github.token }}
      - name: LS Two
        run: ls
      - name: Install dpkg-dev
        run: |
          sudo apt-get update
          sudo apt-get install dpkg-dev
